name: LoginBonus
version: 1.3.0
main: me.kubota6646.loginbonus.Main
api-version: 1.19
author: kubota6646
description: "ログイン報酬を付与するプラグイン。累積ログイン時間で報酬を受け取り、ストリーク機能で報酬が増えます。"

commands:
  rewardstreak:
    description: "現在のストリーク日数を確認するコマンド"
    usage: "/<command>"
  rewardreload:
    description: "設定をリロードするコマンド（OPのみ）"
    usage: "/<command>"
    permission: "lgb01.reload"
  rewardforcegive:
    description: "指定プレイヤーに今日の報酬を強制付与するコマンド（OPのみ）"
    usage: "/<command> <player>"
    permission: "lgb01.admin"
  rewardsetstreak:
    description: "指定プレイヤーのストリーク日数を編集するコマンド（OPのみ）"
    usage: "/<command> <player> <streak>"
    permission: "lgb01.admin"
  rewardresetplaytime:
    description: "指定プレイヤーの累積プレイ時間をリセットするコマンド（OPのみ）"
    usage: "/<command> <player>"
    permission: "lgb01.admin"
  rewardmigrate:
    description: "プレイヤーデータをYAMLとSQLite間で移行するコマンド（OPのみ）"
    usage: "/<command> <from> <to>"
    permission: "lgb01.admin"

permissions:
  lgb01.reload:
    description: "設定をリロードする権限"
    default: op
  lgb01.admin:
    description: "管理者コマンドを使用する権限"

    default: op
